version: "3"

services:
    app:
      build:
        context: app
      ports: 
        - "5000"
    redis:
      image: "redis:latest"
      ports: 
       - "6379:6379"
    nginx:
      image: "nginx:latest"
      ports:
       - "80:80"
       - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./key.pem:/etc/nginx/key.pem
        - ./cert.pem:/etc/nginx/cert.pem